export interface YearEndBonusItem {
  工号: string
  姓名: string
  身份证: string
  最新所属公司: string
  最新所属组织: string
  年终奖工号: string
  年终奖方案名: string
  年度绩效一工号: string
  年度绩效一方案名: string
  年度绩效二工号: string
  年度绩效二方案名: string
  是否管理部人员: string
  钢构部门: string
  人员类别: string
  高企部门: string
  人数: number
  统计年月: number
  岗位编码: string
  岗位名称: string
  入职日期: string
  银行名称: string
  银行卡号: string
  公司职务职称: string
  年度工作日: number
  年度在岗日: number
  年度缺勤日: number
  核定年薪: number
  董事长意见: number
  应发年薪非引进: number
  应发年薪引进: number
  协商年薪: number
  协商月薪: number
  年终奖: number
  年终奖实发: number
  过节费: number
  超利奖: number
  双降奖: number
  技术创新奖: number
  病事假扣款: number
  过失分: number
  过失分考核: number
  年度绩效考核分: number
  得分考核: number
  油卡: number
  音乐家酒: number
  机票商务卡等费用: number
  桃源名筑购房: number
  超支水电费: number
  预支年薪: number
  上海代交规费: number
  劳务公司代交规费: number
  个税: number
  实发绩效: number
}