/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NotFound404ViewNotFound404View: typeof import('./../views/NotFound404View/NotFound404View.vue')['default']
    DialogPlugin: typeof import('tdesign-vue-next')['DialogPlugin']
    EmpViewEmpView: typeof import('./../views/EmpView/EmpView.vue')['default']
    MessagePlugin: typeof import('tdesign-vue-next')['MessagePlugin']
    TestViewTestView: typeof import('./../views/TestView/TestView.vue')['default']
    TList: typeof import('tdesign-vue-next')['List']
    TListItem: typeof import('tdesign-vue-next')['ListItem']
    TPullDownRefresh: typeof import('tdesign-vue-next')['PullDownRefresh']
    TSearch: typeof import('tdesign-vue-next')['Search']
    VanButton: typeof import('vant/es')['Button']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanUploader: typeof import('vant/es')['Uploader']
    VisMemDeskViewVisMemDesk: typeof import('./../views/VisMemDeskView/VisMemDesk.vue')['default']
    VisMemViewVisMem: typeof import('./../views/VisMemView/VisMem.vue')['default']
    ZskViewCompPdfViewer: typeof import('./../views/ZskView/comp/PdfViewer.vue')['default']
    ZskViewZskView: typeof import('./../views/ZskView/ZskView.vue')['default']
  }
}
