name: Build
on:
  push:
    branches:
      - main

jobs:
  build-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Surge
        run: npm install -g surge

      - name: Build project
        run: npm run build

      - name: upload to surge
        run: |
          export DEPLOY_DOMAIN=https://tdesign-mobile-vue-starter-chat.surge.sh
          npx surge --project ./dist --domain $DEPLOY_DOMAIN --token ${{ secrets.TDESIGN_SURGE_TOKEN  }}